### ISSUE TITLE
'TrainiumTrainingArguments' object has no attribute 'ddp_backend' error

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#109]
Am getting the following error message when running the text classification example with the following command on an inf2.8xlarge instance with Neuron SDK `v2.11` and Optimum Neuron `0.0.5`.

```
torchrun --nproc_per_node=2 ~/optimum-neuron/examples/text-classification/run_glue.py \
>     --model_name_or_path bert-base-uncased \
>     --dataset_name philschmid/emotion \
>     --do_train \
>     --do_eval \
>     --bf16 True \
>     --per_device_train_batch_size 32 \
>     --per_device_eval_batch_size 32 \
>     --save_strategy no \
>     --learning_rate 5e-5 \
>     --num_train_epochs 4 \
>     --output_dir bert-emotion
```
The environment is the following:
```
(aws_neuron_venv_pytorch) [ec2-user@ip-172-31-45-112 ~]$ pip list | grep 'torch\|transformers\|accelerate\|optimum\|neuron'
accelerate                    0.20.3
aws-neuronx-runtime-discovery 2.9
libneuronxla                  0.5.326
neuronperf                    1.8.6.0+5dccae385
neuronx-cc                    2.7.0.40+f7c6cf2a3
neuronx-hwm                   2.7.0.3+0092b9d34
optimum                       1.8.8
optimum-neuron                0.0.5
torch                         1.13.1
torch-neuronx                 1.13.1.1.8.0
torch-xla                     1.13.1+torchneuron7
torchvision                   0.14.1
transformers                  4.28.1
```

The stack trace is the following:

```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ec2-user/optimum-neuron/examples/text-classification/run_glue.py:622 in <module>           │
│                                                                                                  │
│   619                                                                                            │
│   620                                                                                            │
│   621 if __name__ == "__main__":                                                                 │
│ ❱ 622 │   main()                                                                                 │
│   623                                                                                            │
│                                                                                                  │
│ /home/ec2-user/optimum-neuron/examples/text-classification/run_glue.py:217 in main               │
│                                                                                                  │
│   214 │   │   # let's parse it to get our arguments.                                             │
│   215 │   │   model_args, data_args, training_args = parser.parse_json_file(json_file=os.path.   │
│   216 │   else:                                                                                  │
│ ❱ 217 │   │   model_args, data_args, training_args = parser.parse_args_into_dataclasses()        │
│   218 │                                                                                          │
│   219 │   # Sending telemetry. Tracking the example usage helps us better allocate resources t   │
│   220 │   # information sent is the one passed as arguments along with your Python/PyTorch ver   │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/hf_argparser.py:44 in  │
│ parse_args_into_dataclasses                                                                      │
│                                                                                                  │
│   41 │   │   )                                                                                   │
│   42 │                                                                                           │
│   43 │   def parse_args_into_dataclasses(self, *args, **kwargs):                                 │
│ ❱ 44 │   │   outputs = super().parse_args_into_dataclasses(*args, **kwargs)                      │
│   45 │   │   for args in outputs:                                                                │
│   46 │   │   │   self.validate_args(args)                                                        │
│   47 │   │   return outputs                                                                      │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/hf_argparser.py:332 in   │
│ parse_args_into_dataclasses                                                                      │
│                                                                                                  │
│   329 │   │   │   inputs = {k: v for k, v in vars(namespace).items() if k in keys}               │
│   330 │   │   │   for k in keys:                                                                 │
│   331 │   │   │   │   delattr(namespace, k)                                                      │
│ ❱ 332 │   │   │   obj = dtype(**inputs)                                                          │
│   333 │   │   │   outputs.append(obj)                                                            │
│   334 │   │   if len(namespace.__dict__) > 0:                                                    │
│   335 │   │   │   # additional namespace.                                                        │
│ in __init__:110                                                                                  │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/training_args.py:82 in │
│ __post_init__                                                                                    │
│                                                                                                  │
│    79 │   │   │   │   │   "The minimal required Transformers version to perform XLA FSDP is "    │
│    80 │   │   │   │   │   f"{TRANSFORMERS_MIN_VERSION_FOR_XLA_FSDP} but {transformers.__versio   │
│    81 │   │   │   │   )                                                                          │
│ ❱  82 │   │   super().__post_init__()                                                            │
│    83 │                                                                                          │
│    84 │   # Needed only to specialize the warning message for FSDP.                              │
│    85 │   @cached_property                                                                       │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/training_args.py:1259 in │
│ __post_init__                                                                                    │
│                                                                                                  │
│   1256 │   │   if (                                                                              │
│   1257 │   │   │   self.framework == "pt"                                                        │
│   1258 │   │   │   and is_torch_available()                                                      │
│ ❱ 1259 │   │   │   and (self.device.type != "cuda")                                              │
│   1260 │   │   │   and (get_xla_device_type(self.device) != "GPU")                               │
│   1261 │   │   │   and (self.fp16 or self.fp16_full_eval)                                        │
│   1262 │   │   ):                                                                                │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/training_args.py:1694 in │
│ device                                                                                           │
│                                                                                                  │
│   1691 │   │   The device used by this process.                                                  │
│   1692 │   │   """                                                                               │
│   1693 │   │   requires_backends(self, ["torch"])                                                │
│ ❱ 1694 │   │   return self._setup_devices                                                        │
│   1695 │                                                                                         │
│   1696 │   @property                                                                             │
│   1697 │   def n_gpu(self):                                                                      │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/utils/generic.py:54 in   │
│ __get__                                                                                          │
│                                                                                                  │
│    51 │   │   attr = "__cached_" + self.fget.__name__                                            │
│    52 │   │   cached = getattr(obj, attr, None)                                                  │
│    53 │   │   if cached is None:                                                                 │
│ ❱  54 │   │   │   cached = self.fget(obj)                                                        │
│    55 │   │   │   setattr(obj, attr, cached)                                                     │
│    56 │   │   return cached                                                                      │
│    57                                                                                            │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/training_args.py:115   │
│ in _setup_devices                                                                                │
│                                                                                                  │
│   112 │   │   │   del os.environ["ACCELERATE_USE_DEEPSPEED"]                                     │
│   113 │   │   │   self._n_gpu = 1                                                                │
│   114 │   │   else:                                                                              │
│ ❱ 115 │   │   │   self.distributed_state = NeuronPartialState(backend=self.ddp_backend)          │
│   116 │   │   │   self._n_gpu = 1                                                                │
│   117 │   │   if not is_sagemaker_mp_enabled():                                                  │
│   118 │   │   │   device = self.distributed_state.device                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'TrainiumTrainingArguments' object has no attribute 'ddp_backend'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ec2-user/optimum-neuron/examples/text-classification/run_glue.py:622 in <module>           │
│                                                                                                  │
│   619                                                                                            │
│   620                                                                                            │
│   621 if __name__ == "__main__":                                                                 │
│ ❱ 622 │   main()                                                                                 │
│   623                                                                                            │
│                                                                                                  │
│ /home/ec2-user/optimum-neuron/examples/text-classification/run_glue.py:217 in main               │
│                                                                                                  │
│   214 │   │   # let's parse it to get our arguments.                                             │
│   215 │   │   model_args, data_args, training_args = parser.parse_json_file(json_file=os.path.   │
│   216 │   else:                                                                                  │
│ ❱ 217 │   │   model_args, data_args, training_args = parser.parse_args_into_dataclasses()        │
│   218 │                                                                                          │
│   219 │   # Sending telemetry. Tracking the example usage helps us better allocate resources t   │
│   220 │   # information sent is the one passed as arguments along with your Python/PyTorch ver   │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/hf_argparser.py:44 in  │
│ parse_args_into_dataclasses                                                                      │
│                                                                                                  │
│   41 │   │   )                                                                                   │
│   42 │                                                                                           │
│   43 │   def parse_args_into_dataclasses(self, *args, **kwargs):                                 │
│ ❱ 44 │   │   outputs = super().parse_args_into_dataclasses(*args, **kwargs)                      │
│   45 │   │   for args in outputs:                                                                │
│   46 │   │   │   self.validate_args(args)                                                        │
│   47 │   │   return outputs                                                                      │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/hf_argparser.py:332 in   │
│ parse_args_into_dataclasses                                                                      │
│                                                                                                  │
│   329 │   │   │   inputs = {k: v for k, v in vars(namespace).items() if k in keys}               │
│   330 │   │   │   for k in keys:                                                                 │
│   331 │   │   │   │   delattr(namespace, k)                                                      │
│ ❱ 332 │   │   │   obj = dtype(**inputs)                                                          │
│   333 │   │   │   outputs.append(obj)                                                            │
│   334 │   │   if len(namespace.__dict__) > 0:                                                    │
│   335 │   │   │   # additional namespace.                                                        │
│ in __init__:110                                                                                  │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/training_args.py:82 in │
│ __post_init__                                                                                    │
│                                                                                                  │
│    79 │   │   │   │   │   "The minimal required Transformers version to perform XLA FSDP is "    │
│    80 │   │   │   │   │   f"{TRANSFORMERS_MIN_VERSION_FOR_XLA_FSDP} but {transformers.__versio   │
│    81 │   │   │   │   )                                                                          │
│ ❱  82 │   │   super().__post_init__()                                                            │
│    83 │                                                                                          │
│    84 │   # Needed only to specialize the warning message for FSDP.                              │
│    85 │   @cached_property                                                                       │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/training_args.py:1259 in │
│ __post_init__                                                                                    │
│                                                                                                  │
│   1256 │   │   if (                                                                              │
│   1257 │   │   │   self.framework == "pt"                                                        │
│   1258 │   │   │   and is_torch_available()                                                      │
│ ❱ 1259 │   │   │   and (self.device.type != "cuda")                                              │
│   1260 │   │   │   and (get_xla_device_type(self.device) != "GPU")                               │
│   1261 │   │   │   and (self.fp16 or self.fp16_full_eval)                                        │
│   1262 │   │   ):                                                                                │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/training_args.py:1694 in │
│ device                                                                                           │
│                                                                                                  │
│   1691 │   │   The device used by this process.                                                  │
│   1692 │   │   """                                                                               │
│   1693 │   │   requires_backends(self, ["torch"])                                                │
│ ❱ 1694 │   │   return self._setup_devices                                                        │
│   1695 │                                                                                         │
│   1696 │   @property                                                                             │
│   1697 │   def n_gpu(self):                                                                      │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/utils/generic.py:54 in   │
│ __get__                                                                                          │
│                                                                                                  │
│    51 │   │   attr = "__cached_" + self.fget.__name__                                            │
│    52 │   │   cached = getattr(obj, attr, None)                                                  │
│    53 │   │   if cached is None:                                                                 │
│ ❱  54 │   │   │   cached = self.fget(obj)                                                        │
│    55 │   │   │   setattr(obj, attr, cached)                                                     │
│    56 │   │   return cached                                                                      │
│    57                                                                                            │
│                                                                                                  │
│ /opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/training_args.py:115   │
│ in _setup_devices                                                                                │
│                                                                                                  │
│   112 │   │   │   del os.environ["ACCELERATE_USE_DEEPSPEED"]                                     │
│   113 │   │   │   self._n_gpu = 1                                                                │
│   114 │   │   else:                                                                              │
│ ❱ 115 │   │   │   self.distributed_state = NeuronPartialState(backend=self.ddp_backend)          │
│   116 │   │   │   self._n_gpu = 1                                                                │
│   117 │   │   if not is_sagemaker_mp_enabled():                                                  │
│   118 │   │   │   device = self.distributed_state.device                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'TrainiumTrainingArguments' object has no attribute 'ddp_backend'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18524) of binary: /opt/aws_neuron_venv_pytorch/bin/python3.8
Traceback (most recent call last):
  File "/opt/aws_neuron_venv_pytorch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ec2-user/optimum-neuron/examples/text-classification/run_glue.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-23_17:14:24
  host      : ip-172-31-45-112.us-east-2.compute.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 18525)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-23_17:14:24
  host      : ip-172-31-45-112.us-east-2.compute.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 18524)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by mmcclean-aws** [comment]
Same error happens with Neuron SDK v2.11
