### ISSUE TITLE
Vision Transformer funetuning ended up with std::bad_alloc error

### ISSUE THREAD

**Issue by kct22aws** [huggingface/optimum-neuron#166]
Trying to run ViT finetuning example as shown in https://github.com/huggingface/optimum-neuron/blob/main/examples/image-classification/run_image_classification.py

After 40minutes compilation, end up with 

```
Compiler status PASS
2023-Aug-09 19:30:32.0804 42376:43530 ERROR  TDRV:dma_queue_init_batch_execute            failed to init dma queue batch
2023-Aug-09 19:30:32.0804 42376:43530 ERROR  TDRV:init_dma                                failed to init dma queue batch
2023-Aug-09 19:30:32.0804 42376:43530 ERROR  NMGR:dlr_kelf_start_no_lock                  Model (1011) start failed for VNC=0, ret: 2
2023-Aug-09 19:30:32.0804 42376:43530 ERROR  NMGR:tpbs_infer_lock                         Failed to start model
2023-Aug-09 19:30:32.0804 42376:43530 ERROR  NMGR:dlr_infer                               Failed to acquire infer locks
2023-08-09 19:30:32.806075: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at tpu_execute_op.cc:266 : INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
2023-08-09 19:30:35.211775: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] StackTrace:
2023-08-09 19:30:35.211815: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** Begin stack trace ***
2023-08-09 19:30:35.211819: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        tsl::CurrentStackTrace()
2023-08-09 19:30:35.211822: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::ReportComputationError(tsl::Status const&, absl::lts_20220623::Span<xla::XlaComputation const* const>, absl::lts_20220623::Span<xla::Shape const* const>)
2023-08-09 19:30:35.211826: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2023-08-09 19:30:35.211834: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-09 19:30:35.211838: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2023-08-09 19:30:35.211841: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-09 19:30:35.211844: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-09 19:30:35.211847: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-09 19:30:35.211850: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        clone
2023-08-09 19:30:35.211853: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** End stack trace ***
2023-08-09 19:30:35.211856: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-09 19:30:35.211860: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Status: INVALID_ARGUMENT: From /job:localservice/replica:0/task:0:
2023-08-09 19:30:35.211863: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 2 root error(s) found.
2023-08-09 19:30:35.211866: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (0) INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
2023-08-09 19:30:35.211870: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-08-09 19:30:35.211873: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[XRTExecute_G12]]
2023-08-09 19:30:35.211876: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (1) INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
2023-08-09 19:30:35.211880: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-08-09 19:30:35.211884: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 successful operations.
2023-08-09 19:30:35.211887: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 derived errors ignored.
2023-08-09 19:30:35.211890: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Recent warning and error logs:
2023-08-09 19:30:35.211894: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
Traceback (most recent call last):
  File "run_image_classification.py", line 399, in <module>
    main()
  File "run_image_classification.py", line 373, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/utils/patching.py", line 180, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/trainers.py", line 457, in _inner_training_loop
    return super()._inner_training_loop(
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 1880, in _inner_training_loop
    self.optimizer.step()
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/accelerate/optimizer.py", line 79, in step
    xm.optimizer_step(self.optimizer, optimizer_args=optimizer_args)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 1091, in optimizer_step
    loss = optimizer.step(**optimizer_args)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/optimization.py", line 466, in step
    exp_avg.mul_(beta1).add_(grad, alpha=(1.0 - beta1))
RuntimeError: INVALID_ARGUMENT: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
         [[{{node XRTExecute}}]]
         [[XRTExecute_G12]]
  (1) INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
         [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_xla/__init__.py", line 133, in _prepare_to_exit
    _XLAC._prepare_to_exit()
RuntimeError: INVALID_ARGUMENT: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
         [[{{node XRTExecute}}]]
         [[XRTExecute_G12]]
  (1) INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
         [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INVALID_ARGUMENT: tensorflow/libtpu/neuron/nrt_adaptor.cc:423:Invalid input_map: nrt_execute: status=2, error message="Invalid argument".
  3%|▎         | 11/390 [25:21<14:33:33, 138.30s/it]                                                                                        
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc```

**Comment by kct22aws** [comment]
Any idea or suggstions?
