### ISSUE TITLE
dynamic_batch_size=True doesn't work for models exported with NeuronModelForSequenceClassification

### ISSUE THREAD

**Issue by samir-souza** [huggingface/optimum-neuron#189]
**optimum-neuron: 0.0.8, 0.0.9 and 0.0.10.dev0**

Error when you try to compile a bert-base-uncased to inferentia2, using NeuronModelForSequenceClassification (probably it is failing for other tasks [and models?] as well).

Even enabling dynamic_batch_size=True during model compilation, an error occurs when you try to run the model with batch_size > 1. When trying to execute the compiled with batch_size > 1 you get the exception:
`ValueError: Unable to pad input_ids with shape: torch.Size([2, 256]) on dimension 0 as input shapes must be inferior than the static shapes used for compilation: torch.Size([1, 256]), unless you set `dynamic_batch_size=True` during the compilation.`

COMPILE
```
from transformers import AutoTokenizer
from optimum.neuron import NeuronModelForSequenceClassification

model_name='bert-base-uncased'

input_shapes = {"batch_size": 1, "sequence_length": 256}
model = NeuronModelForSequenceClassification.from_pretrained(
    model_name, export=True, dynamic_batch_size=True, **input_shapes
)
model.save_pretrained('neuron')
```

INVOKE
```
from transformers import AutoTokenizer
from optimum.neuron import NeuronModelForSequenceClassification

max_sen_len=256
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
tokenizer.pad_token_id = 0
tokenizer.model_max_length = max_sen_len

text = [" text 1", "text 2"]

inputs = tokenizer(text, padding=True, truncation=True, return_tensors="pt")
print(inputs['input_ids'].shape)
model = NeuronModelForSequenceClassification.from_pretrained("neuron/", dynamic_batch_size=True)
model.preprocessors = None
logits = model(**inputs).logits

print(model.config.id2label[logits.argmax().item()])
```

ERROR

```
Traceback (most recent call last):
  File "../invoke.py", line 19, in <module>
    logits = model(**inputs).logits
  File "/home/ubuntu/Optimum/optimvenv/lib/python3.8/site-packages/optimum/modeling_base.py", line 90, in __call__
    return self.forward(*args, **kwargs)
  File "/home/ubuntu/Optimum/optimvenv/lib/python3.8/site-packages/optimum/neuron/modeling.py", line 369, in forward
    with self.neuron_padding_manager(neuron_inputs) as inputs:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/ubuntu/Optimum/optimvenv/lib/python3.8/site-packages/optimum/neuron/modeling_base.py", line 502, in neuron_padding_manager
    inputs = tuple(self._pad_to_compiled_shape(inputs).values())
  File "/home/ubuntu/Optimum/optimvenv/lib/python3.8/site-packages/optimum/neuron/modeling_base.py", line 492, in _pad_to_compiled_shape
    self._raise_if_invalid_padding(input_name, input_tensor, target_shapes, to_pad, 0)
  File "/home/ubuntu/Optimum/optimvenv/lib/python3.8/site-packages/optimum/neuron/modeling_base.py", line 448, in _raise_if_invalid_padding

ValueError: Unable to pad input_ids with shape: torch.Size([2, 256]) on dimension 0 as input shapes must be inferior than the static shapes used for compilation: torch.Size([1, 256]), unless you set `dynamic_batch_size=True` during the compilation.

```

**Comment by JingyaHuang** [comment]
Thanks for reporting, I can confirm that the model was compiled with dynamic batching. The error comes from the fact that `dynamic_batch_size` was not correctly inferred from the exported model's config file, you can find the fix here: #190

**Comment by samir-souza** [comment]
Hi @JingyaHuang! Your patch fixed the problem. Thanks!

**Comment by JingyaHuang** [comment]
Hi @samir-souza, I just merged the fix. FYI, you might need to upgrade your transformers to 4.32 as I also fixed some breaking changes introduced by the trfrs release.
