### ISSUE TITLE
"List index out of range" error when using BART-base summarization model

### ISSUE THREAD

**Issue by njbrake** [huggingface/optimum-neuron#19]
Hi, 

when running training of BART-base on a `trn1.2xlarge` using the command

```
 torchrun --nproc_per_node=2 run_summarization.py
```

I receive the below compilation error, I am wondering if you have any tips you might be able to provide about how to understand what is going wrong? From the output I can't tell whether it's an error on the optimum-neuron side, or the neuron-sdk (neuronx-cc) side.

```

.......03/17/2023 01:52:37 PM ERROR 3541 [Tensorizer]: Transformation error on operator: _scatter.4
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: ***************************************************************
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:  An Internal Compiler Error has occurred
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: ***************************************************************
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: 
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: Error message:  list index out of range
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: 
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: Error class:    IndexError
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: Error location: Unknown
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: Command line:   /opt/aws_neuron_venv_pytorch/bin/neuronx-cc --target=trn1 compile --framework XLA /tmp/MODULE_1_SyncTensorsGraph.30344_9843381109720227859.hlo.pb --output /var/tmp/neuron-compile-cache/USER_neuroncc-2.4.0.21+b7621be18/MODULE_9843381109720227859/MODULE_1_SyncTensorsGraph.30344_9843381109720227859/87416364-87e0-42b6-b9e8-ee59db979679/MODULE_1_SyncTensorsGraph.30344_9843381109720227859.neff --verbose=35
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: 
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: Internal details:
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/CommandDriver.py", line 235, in neuronxcc.driver.CommandDriver.CommandDriver.run
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1014, in neuronxcc.driver.commands.CompileCommand.CompileCommand.run
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 965, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 990, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 994, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 300, in neuronxcc.driver.Job.SingleInputJob.run
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 326, in neuronxcc.driver.Job.SingleInputJob.runOnState
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/Pipeline.py", line 30, in neuronxcc.driver.Pipeline.Pipeline.runSingleInput
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 300, in neuronxcc.driver.Job.SingleInputJob.run
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 326, in neuronxcc.driver.Job.SingleInputJob.runOnState
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/jobs/Frontend.py", line 591, in neuronxcc.driver.jobs.Frontend.Frontend.runSingleInput
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/driver/jobs/Frontend.py", line 387, in neuronxcc.driver.jobs.Frontend.Frontend.runXLAFrontend
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 168, in neuronxcc.starfish.penguin.Frontend.tensorizeXla
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 243, in neuronxcc.starfish.penguin.Frontend.tensorizeXlaImpl
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 244, in neuronxcc.starfish.penguin.Frontend.tensorizeXlaImpl
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 266, in neuronxcc.starfish.penguin.Frontend.tensorizeXlaImpl
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Compile.py", line 183, in neuronxcc.starfish.penguin.Compile.compile_cu
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Compile.py", line 185, in neuronxcc.starfish.penguin.Compile.compile_cu
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Compile.py", line 222, in neuronxcc.starfish.penguin.Compile.compile_cu
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 432, in neuronxcc.starfish.penguin.DotTransform.PassManager.transformFunction
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 440, in neuronxcc.starfish.penguin.DotTransform.PassManager.transformFunction
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 142, in neuronxcc.starfish.penguin.DotTransform.DotTransform.runOnFunction
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 196, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 178, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 208, in neuronxcc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 210, in neuronxcc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 211, in neuronxcc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 240, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 241, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 334, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transformFunction
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 329, in neuronxcc.starfish.penguin.DotTransform.DotTransform.runTransforms
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 318, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transformStmts
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 133, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transform
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 366, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transformBasicBlock
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 369, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transformBasicBlock
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 133, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transform
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 356, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transformStmt
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 133, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transform
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaISel.py", line 549, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaISel.SundaISel.transformTGenericAtomicRMWOperator
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/tonga/passes/TongaISel.py", line 174, in neuronxcc.starfish.penguin.targets.tonga.passes.TongaISel.CodegenBase.codegenMacro
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/tonga/passes/TongaISel.py", line 200, in neuronxcc.starfish.penguin.targets.tonga.passes.TongaISel.CodegenBase.codegenInsts
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/tonga/passes/TongaISel.py", line 225, in neuronxcc.starfish.penguin.targets.tonga.passes.TongaISel.CodeGen.codegenInst
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/tonga/passes/TongaISel.py", line 214, in neuronxcc.starfish.penguin.targets.tonga.passes.TongaISel.CodeGen.dispatch_codegen
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaISel.py", line 408, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaISel.ScatterCodegen.codegenGenericAtomicRMW
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/tonga/passes/TongaISel.py", line 321, in neuronxcc.starfish.penguin.targets.tonga.passes.TongaISel.CodeGen.codegenGenericAccess
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: 
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: Version information:
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   NeuronX Compiler version 2.4.0.21+b7621be18
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   HWM version 2.4.0.1-90172456c
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   NEFF version Dynamic
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   TVM not available
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   NumPy version 1.20.0
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]:   MXNet not available
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: 
03/17/2023 01:52:37 PM ERROR 3541 [neuronx-cc]: Artifacts stored in: /home/ssm-user/scm/scribe_summarization_huggingface/data/neuronxcc-rcxp7i5p

Compiler status ERROR
2023-03-17 13:52:38.000614: ERROR ||NCC_WRAPPER||: There was a compilation error for /tmp/MODULE_1_SyncTensorsGraph.30344_9843381109720227859.hlo.pb graph. Returning with an errored graph
2023-03-17 13:52:39.090977: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
2023-03-17 13:52:39.099414: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
  0%|                                                                                                                                                                                              | 2/10068 [02:19<228:11:10, 81.61s/it]2023-03-17 13:52:39.262232: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] StackTrace:
2023-03-17 13:52:39.262272: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** Begin stack trace ***
2023-03-17 13:52:39.262283: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        tsl::CurrentStackTrace()
2023-03-17 13:52:39.262293: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::ReportComputationError(tsl::Status const&, absl::lts_20220623::Span<xla::XlaComputation const* const>, absl::lts_20220623::Span<xla::Shape const* const>)
2023-03-17 13:52:39.262300: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2023-03-17 13:52:39.262322: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.262331: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2023-03-17 13:52:39.262337: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.262345: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.262354: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.262362: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        clone
2023-03-17 13:52:39.262370: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** End stack trace ***
2023-03-17 13:52:39.262378: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.262386: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Status: INTERNAL: From /job:localservice/replica:0/task:0:
2023-03-17 13:52:39.262395: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 2 root error(s) found.
2023-03-17 13:52:39.262403: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (0) INTERNAL: neuronx-cc compilation failed.
2023-03-17 13:52:39.262411: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-03-17 13:52:39.262419: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[XRTExecute_G15]]
2023-03-17 13:52:39.262427: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (1) INTERNAL: neuronx-cc compilation failed.
2023-03-17 13:52:39.262436: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-03-17 13:52:39.262444: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 successful operations.
2023-03-17 13:52:39.262452: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 derived errors ignored.
2023-03-17 13:52:39.262460: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Recent warning and error logs:
2023-03-17 13:52:39.262469: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
Traceback (most recent call last):
  File "/home/ssm-user/scm/scribe_summarization_huggingface/src/hf_summ/train.py", line 269, in train
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/trainer.py", line 1543, in train
    return inner_training_loop(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/trainer.py", line 1765, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/parallel_loader.py", line 34, in __next__
    return self.next()
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 951, in mark_step
    torch_xla._XLAC._xla_step_marker(
RuntimeError: INTERNAL: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: neuronx-cc compilation failed.
         [[{{node XRTExecute}}]]
         [[XRTExecute_G15]]
  (1) INTERNAL: neuronx-cc compilation failed.
         [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../src/run_summarization.py", line 15, in <module>
    train()
  File "/home/ssm-user/scm/scribe_summarization_huggingface/src/hf_summ/train.py", line 374, in train
    return results
UnboundLocalError: local variable 'results' referenced before assignment
2023-03-17 13:52:39.277978: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] StackTrace:
2023-03-17 13:52:39.278010: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** Begin stack trace ***
2023-03-17 13:52:39.278020: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        tsl::CurrentStackTrace()
2023-03-17 13:52:39.278030: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::ReportComputationError(tsl::Status const&, absl::lts_20220623::Span<xla::XlaComputation const* const>, absl::lts_20220623::Span<xla::Shape const* const>)
2023-03-17 13:52:39.278040: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2023-03-17 13:52:39.278046: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.278055: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2023-03-17 13:52:39.278064: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.278072: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.278081: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.278090: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        clone
2023-03-17 13:52:39.278098: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** End stack trace ***
2023-03-17 13:52:39.278106: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-03-17 13:52:39.278116: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Status: INTERNAL: From /job:localservice/replica:0/task:0:
2023-03-17 13:52:39.278125: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 2 root error(s) found.
2023-03-17 13:52:39.278134: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (0) INTERNAL: neuronx-cc compilation failed.
2023-03-17 13:52:39.278142: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-03-17 13:52:39.278151: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[XRTExecute_G15]]
2023-03-17 13:52:39.278160: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (1) INTERNAL: neuronx-cc compilation failed.
2023-03-17 13:52:39.278169: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-03-17 13:52:39.278177: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 successful operations.
2023-03-17 13:52:39.278186: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 derived errors ignored.
2023-03-17 13:52:39.278195: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Recent warning and error logs:
2023-03-17 13:52:39.278204: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
2023-03-17 13:52:39.278213: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
Traceback (most recent call last):
  File "/home/ssm-user/scm/scribe_summarization_huggingface/src/hf_summ/train.py", line 269, in train
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/trainer.py", line 1543, in train
    return inner_training_loop(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/trainer.py", line 1765, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/parallel_loader.py", line 34, in __next__
    return self.next()
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 951, in mark_step
    torch_xla._XLAC._xla_step_marker(
RuntimeError: INTERNAL: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: neuronx-cc compilation failed.
         [[{{node XRTExecute}}]]
         [[XRTExecute_G15]]
  (1) INTERNAL: neuronx-cc compilation failed.
         [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../src/run_summarization.py", line 15, in <module>
    train()
  File "/home/ssm-user/scm/scribe_summarization_huggingface/src/hf_summ/train.py", line 374, in train
    return results
UnboundLocalError: local variable 'results' referenced before assignment
  0%|                                                                                                                                                                                              | 2/10068 [02:20<195:46:22, 70.02s/it]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1585) of binary: /opt/aws_neuron_venv_pytorch/bin/python3.8
Traceback (most recent call last):
  File "/opt/aws_neuron_venv_pytorch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../src/run_summarization.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-17_13:52:43
  host      : ip-10-255-154-196.ec2.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1586)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-17_13:52:43
  host      : ip-10-255-154-196.ec2.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1585)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(aws_neuron_venv_pytorch) [ssm-user@ip-10-255-154-196 data]$ 
```

**Comment by philschmid** [comment]
Hello @njbrake,

Thank you for opening the issue! in the logs i can see `train.py` being used and in the beginning you are saying you are using the `run_summarization.py` example. Did you copy it or is the `train.py` another script? 
Did you pass any hyperparameter along? , e.g. model id, dataset, batchsize etc.

**Comment by michaelbenayoun** [comment]
Hi @njbrake,
I see the error being:
```plain
UnboundLocalError: local variable 'results' referenced before assignment
```
But from experience, what could be happening is that you are using a batch size that is too big. 
What is the `per-device-batch-size`? 

Here some tips:

- Use the `-bf16` flag to perform training in BF16, unless it gives bad accuracy, it is the recommended way to go on Trainium, it will allow you to use a bigger batch size.
- The batch size choice will be dependent on the sequence length you are dealing with. For summarization, the source sequence length is usually big (`1024`) so I would recommend using a small per-device batch size, like 2 (maybe 3-4 can fit)

**Comment by njbrake** [comment]
Hi @michaelbenayoun and @philschmid, Thanks for the fast response!

 sorry that "local variable 'results'" error was irrelevant, it was an error that came up because of the error that was thrown by neuron.

the run_summarization.py script is a simple wrapper that calls the train.py script for my case.

I tried adding the bf16 flag but that didn't help either. here are my hyperparameters.

```
{
    "model_name_or_path": "facebook/bart-large",
    "dataset_name" : "my_dataset",
    "save_predictions" : false,
    "do_train": true,
    "do_eval": true,
    "do_predict": true,
    "max_source_length": 1024,
    "max_seq_length": 1024,
    "max_target_length": 1024,
    "predict_with_generate": true,
    "num_beams": 5,
    "generation_num_beams": 5,
    "generation_max_length": 512,
    "generation_no_repeat_ngram_size": 3,
    "label_smoothing_factor": 0.1,
    "per_device_train_batch_size": 1,
    "per_device_eval_batch_size": 1,
    "num_train_epochs": 2,
    "warmup_steps": 200,
    "learning_rate": 4e-5,
    "lr_scheduler_type": "polynomial",
    "weight_decay": 0.0001,
    "max_grad_norm": 0.1,
    "evaluation_strategy": "steps",
    "logging_strategy": "steps",
    "save_strategy": "steps",
    "eval_steps": 100,
    "logging_steps": 100,
    "save_steps": 100,
    "load_best_model_at_end": true,
    "metric_for_best_model": "rougeL",
    "early_stopping_patience": 5,
    "save_total_limit": 3,
    "pad_to_multiple_of": 8,
    "pad_to_max_length": true,
    "gradient_checkpointing": false,
    "fp16": false,
    "bf16": true
}
```
I tried with setting bf16 to false, both produced that same error.

**Comment by njbrake** [comment]
Oh awesome! I’ll do that. Thanks for the support on this 💯  . Any idea when generation might be supported? That’s pretty important for my team that has factuality based eval metrics that rely upon generation.

**Comment by michaelbenayoun** [comment]
I just ran the following command:

```bash
python examples/summarization/run_summarization.py --model_name_or_path facebook/bart-base --dataset_name cnn_dailymail --dataset_config_name 3.0.0 --do_train --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --max_source_length 1024 --max_target_length 128 --overwrite_output_dir --output_dir test_bart_base --bf16
```

And it works nicely.

I agree that the error message is not helpful at all, from my experience the issue is usually from not having enough memory.

Could you try this:
```
max_source_length = 100
max_target_length = 100
```

Just to check if this memory related?

**Comment by njbrake** [comment]
Ok, I ran the command you pasted and it worked for me as well. So I guess this at least helps to narrow it down that it's something to do with my particular hyperparameters. Looks like I won't quite get to it today, but I'll put in some more work on Monday to try to see if I can narrow down what hyperparameter is causing it. At least now that at least I have that one script running, I can slowly add in my hyperparameter tweaks to see where it breaks!

If these issues are indeed related to memory, would the problems be resolved if I switched to the trn1.24xlarge instance?

**Comment by njbrake** [comment]
Found it!

if you add `--label_smoothing_factor 0.1`, that will reproduce the error

```
03/20/2023 12:30:05 PM ERROR 3459 [Tensorizer]: Transformation error on operator: _scatter.2
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: ***************************************************************
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]:  An Internal Compiler Error has occurred
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: ***************************************************************
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: 
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: Error message:  list index out of range
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: 
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: Error class:    IndexError
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: Error location: Unknown
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: Command line:   /opt/aws_neuron_venv_pytorch/bin/neuronx-cc --target=trn1 compile --framework XLA /tmp/MODULE_1_SyncTensorsGraph.28326_10581472026669971527_ip-10-255-154-196.ec2.internal-353f0e91-2609-5f7540e46efd9.hlo.pb --output /var/tmp/neuron-compile-cache/USER_neuroncc-2.4.0.21+b7621be18/MODULE_10581472026669971527/MODULE_1_SyncTensorsGraph.28326_10581472026669971527_ip-10-255-154-196.ec2.internal-353f0e91-2609-5f7540e46efd9/44a76ae5-b288-4580-8565-d89aa4baab01/MODULE_1_SyncTensorsGraph.28326_10581472026669971527_ip-10-255-154-196.ec2.internal-353f0e91-2609-5f7540e46efd9.neff --model-type=transformer --verbose=35
03/20/2023 12:30:05 PM ERROR 3459 [neuronx-cc]: 
```

**Comment by michaelbenayoun** [comment]
Nice, I am able to reproduce!
Will keep you posted

**Comment by michaelbenayoun** [comment]
FYI https://github.com/aws-neuron/aws-neuron-sdk/issues/643#issuecomment-1500641091
