### ISSUE TITLE
Inf2 Modified Llama 2 Compilation Error 

### ISSUE THREAD

**Issue by liechtym** [huggingface/optimum-neuron#385]
I'm running on a Inf2.8xlarge with "AMI Deep Learning AMI Neuron PyTorch 1.13 (Ubuntu 20.04) 20231205". 

I updated to the latest Neuron version via `python -m pip install --upgrade neuronx-cc==2.* --pre torch-neuronx==2.0.* torchvision`

Installed via `pip install optimum[neuronx]`

Here's my code:
```
from optimum.neuron import NeuronModelForCausalLM
compiler_args = {"num_cores": 2, "auto_cast_type": 'fp16'}
input_shapes = {"batch_size": 1, "sequence_length": 2048}

model = NeuronModelForCausalLM.from_pretrained(
        "wangrongsheng/MiniGPT-4-LLaMA-7B",
        export=True,
        **compiler_args,
        **input_shapes)
        
model.save_pretrained("compiled_minpgt4_llama_7b")
```

Here's the trace:
```
Traceback (most recent call last):
  File "convert_neuron.py", line 4, in <module>
    model = NeuronModelForCausalLM.from_pretrained(
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/modeling_decoder.py", line 153, in _from_transformers
    return cls._from_pretrained(checkpoint_dir, config)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/modeling_decoder.py", line 209, in _from_pretrained
    neuronx_model = exporter.neuronx_class.from_pretrained(
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers_neuronx/module.py", line 145, in from_pretrained
    state_dict_path = os.path.join(pretrained_model_path, 'pytorch_model.bin')
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpoyfc_s_s/pytorch_model.bin'
```

Wasn't sure where to even start to debug this, so wanted to see if I could get some help!

**Comment by codeeplearning** [comment]
Hi! I am facing this issue too. Can you help how did you fix it?

**Comment by liechtym** [comment]
@codeeplearning the issue was in tranfomers_neuronx. They've resolved it you just need to update. See this issue: https://github.com/aws-neuron/transformers-neuronx/issues/67

**Comment by codeeplearning** [comment]
Thanks for the quick response. I referred that. Made some progress. Now I am getting this error "RuntimeError: nrt_load_collectives status=2" similar to you. I saw the solution to upgrade to neuron 2.16 but I am lost in the documentation as I couldn't find the installation step. I checked these too. 
https://pip.repos.neuron.amazonaws.com/
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#release-artifacts

Can you please help with me the exact command?

**Comment by liechtym** [comment]
@codeeplearning 
You have to update the associated packages on your system. I'm using Ubuntu 20 so I used the following command (might have missed a package or two here, but you can see the list of packages to update on the 2.16 release docs):
```
sudo apt-get install --only-upgrade aws-neuronx-dkms aws-neuronx-runtime-lib aws-neuronx-tools aws-neuronx-k8-plugin aws-neuronx-k8-scheduler tensorflow-model-server-neuronx aws-neuronx-collectives
 -y
```
