### ISSUE TITLE
optimum-neuron with 2.16 Transformers-Neuronx: AttributeError: 'NoneType' object has no attribute 'get_kernels'

### ISSUE THREAD

**Issue by jeffhataws** [huggingface/optimum-neuron#388]
Using optimum-neuron, following blog https://huggingface.co/blog/inferentia-llama2 but need to install from TOT like "pip install git+https://github.com/huggingface/optimum-neuron.git" and log into Huggingface using "huggingface-cli login", then run the following:

```
from optimum.neuron import pipeline

p = pipeline('text-generation', 'aws-neuron/Llama-2-7b-hf-neuron-budget')
p("My favorite place on earth is", max_new_tokens=64, do_sample=True, top_k=50)

```
Using TNx release candidate from 2.16, get:

```
(aws_neuron_venv) ubuntu@ip-10-4-213-64:~$ python llama_infer.py                   
Fetching 316 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 316/316 [00:00<00:00, 6689.85it/s]
Traceback (most recent call last):                                                
  File "llama_infer.py", line 3, in <module>                         
    p = pipeline('text-generation', 'aws-neuron/Llama-2-7b-hf-neuron-budget')                                                                                        
  File "/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/optimum/neuron/pipelines/transformers/base.py", line 229, in pipeline
    model, model_id, tokenizer, feature_extractor = load_pipeline(    
  File "/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/optimum/neuron/pipelines/transformers/base.py", line 122, in load_pipeline
    model = neuronx_model_class.from_pretrained(
  File "/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/optimum/neuron/modeling_decoder.py", line 221, in _from_pretrained
    neuronx_model._load_compiled_artifacts(compiled_path)
  File "/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/transformers_neuronx/base.py", line 105, in _load_compiled_artifacts
    nbs_obj.set_neff_bytes(directory)
  File "/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/transformers_neuronx/base.py", line 378, in set_neff_bytes
    for kernel in self.get_all_kernels(): 
  File "/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/transformers_neuronx/decoder.py", line 556, in get_all_kernels
    return self.program.get_kernels()
AttributeError: 'NoneType' object has no attribute 'get_kernels'

```

**Comment by jeffhataws** [comment]
https://github.com/huggingface/optimum-neuron/pull/387 should fix this issue

**Comment by jeffhataws** [comment]
https://github.com/huggingface/optimum-neuron/pull/387 is merged. Thanks.
