### ISSUE TITLE
optimum-neuron with Neuron SDK 2.16 Transformers-Neuronx: ValueError: Attempted to use an uninitialized parameter in <method 'detach' of 'torch._C._TensorBase' objects>

### ISSUE THREAD

**Issue by jeffhataws** [huggingface/optimum-neuron#389]
Using optimum-neuron, following blog https://huggingface.co/blog/inferentia-llama2 but need to install from TOT like "pip install git+https://github.com/huggingface/optimum-neuron.git" and log into Huggingface using "huggingface-cli login", then run the following code to convert HF model to Neuron model:
```
from optimum.neuron import NeuronModelForCausalLM

compiler_args = {"num_cores": 2, "auto_cast_type": "fp16"}
input_shapes = {"batch_size": 1, "sequence_length": 2048}
model  = NeuronModelForCausalLM.from_pretrained(
        "NousResearch/Llama-2-7b-chat-hf",
        export=True,
        **compiler_args,
        **input_shapes
        )

model.save_pretrained("./saved_model")
```
Using TNx release candidate from 2.16, get:
```
Downloading generation_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 179/179 [00:00<00:00, 65.8kB/s]
/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:381: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:386: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:527: UserWarning: The generation config instance is invalid -- `.validate()` throws warnings and/or exceptions. Fix these issues to save the configuration. This warning will be raised to an exception in v4.34.

Thrown during validation:
`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
Traceback (most recent call last):
  File "llama_convert.py", line 5, in <module>
    model  = NeuronModelForCausalLM.from_pretrained(
  File "/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/optimum/neuron/modeling_decoder.py", line 155, in _from_transformers
    return cls._from_pretrained(checkpoint_dir, config)
  File "/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/optimum/neuron/modeling_decoder.py", line 227, in _from_pretrained
    neuronx_model.to_neuron()
  File "/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/transformers_neuronx/base.py", line 60, in to_neuron
    self.load_weights()
  File "/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/transformers_neuronx/llama/model.py", line 88, in load_weights
    new_layer.add_pre_attention_layer_norm(layer.input_layernorm.weight.detach(), None)
  File "/home/ubuntu/aws_neuron_venv_r2.16_beta/lib/python3.8/site-packages/torch/nn/parameter.py", line 144, in __torch_function__
    raise ValueError(
ValueError: Attempted to use an uninitialized parameter in <method 'detach' of 'torch._C._TensorBase' objects>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions
```
Using Neuron SDK release 2.15, I see normal Neuron compilations using the same script above:
```
/home/ubuntu/aws_neuron_venv/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:557: UserWarning: The generation config instance is invalid 
-- `.validate()` throws warnings and/or exceptions. Fix these issues to save the configuration. This warning will be raised to an exception in v4.34.

Thrown during validation:
`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or
 unset `temperature`.
  warnings.warn(
2023-12-20 18:14:22.000972:  11268  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2023-12-20 18:14:22.000974:  11268  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ubunt
u/neuroncc_compile_workdir/5473db22-21bf-4aca-9310-b946afa38171/model.MODULE_7f609f02520a89fd33a3+8737852b.hlo.pb', '--output', '/tmp/ubuntu/neuroncc_compile_workdi
r/5473db22-21bf-4aca-9310-b946afa38171/model.MODULE_7f609f02520a89fd33a3+8737852b.neff', '--model-type=transformer', '--model-type=transformer', '--verbose=35']
2023-12-20 18:14:23.000033:  11269  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache                                                        2023-12-20 18:14:23.000035:  11269  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ubuntu/neuroncc_compile_workdir/9eb7ab3a-6087-42b4-8972-4e1e3fae29aa/model.MODULE_53d471343a620ce6304a+8737852b.hlo.pb', '--output', '/tmp/ubuntu/neuroncc_compile_workdi
r/9eb7ab3a-6087-42b4-8972-4e1e3fae29aa/model.MODULE_53d471343a620ce6304a+8737852b.neff', '--model-type=transformer', '--model-type=transformer', '--verbose=35']
2023-12-20 18:14:23.000069:  11270  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2023-12-20 18:14:23.000070:  11270  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ubunt
u/neuroncc_compile_workdir/195eeb8f-59ac-4cbb-bb60-e698be1b4db5/model.MODULE_6f2c8e5757e0da0b8d4e+8737852b.hlo.pb', '--output', '/tmp/ubuntu/neuroncc_compile_workdi
r/195eeb8f-59ac-4cbb-bb60-e698be1b4db5/model.MODULE_6f2c8e5757e0da0b8d4e+8737852b.neff', '--model-type=transformer', '--model-type=transformer', '--verbose=35']
2023-12-20 18:14:23.000077:  11271  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2023-12-20 18:14:23.000079:  11271  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ubunt
u/neuroncc_compile_workdir/c611f833-d3c5-4a28-a2a4-3c78fb655eed/model.MODULE_7f13d0c151e309e927c0+8737852b.hlo.pb', '--output', '/tmp/ubuntu/neuroncc_compile_workdi

```

**Comment by dacorvo** [comment]
AWS Neuron SDK 2.16 is not supported yet: `optimum-neuron` will force the installation of AWS Neuron SDK 2.15 packages for `neuronx-cc`, `transformers-neuronx`, `neuronx-distributed`.

**Comment by dacorvo** [comment]
Fixed in https://github.com/huggingface/optimum-neuron/releases/tag/v0.0.17.
