### ISSUE TITLE
Errors running BERT on Optimum-Neuron with torch-neuronx 2.1: `cannot import name 'NeuronTrainer`, followed by ``error: argument --model-type: invalid choice: transformer-O2``, followed by BF16 mixed precision error,  finally with "AssertionError: data parallel group is not initialized"

### ISSUE THREAD

**Issue by jeffhataws** [huggingface/optimum-neuron#446]
@philschmid  @dacorvo 

There are multiple issues here so will need to break into different issues.

When I followed https://huggingface.co/docs/optimum-neuron/tutorials/fine_tune_bert, I first encountered "" when I installed using ``pip install optimum[neuron]`` in python3.8 environment:
```
optimum                       1.16.2
optimum-neuron                0.0.1
```
I get ``ImportError: cannot import name 'NeuronTrainer' from 'optimum.neuron'``. This I worked around by installing directly TOT ``pip install git+https://github.com/huggingface/optimum-neuron.git``
```
optimum                       1.16.2
optimum-neuron                0.0.18.dev0
```
Next I get ``error: argument --model-type: invalid choice: transformer-O2``:

```
torchrun --nproc_per_node=2 train.py  --model_id bert-base-uncased  --dataset_path lm_dataset  --lr 5e-5  --per_device_train_batch_size 16 --bf16 True  --epochs 3

...

ValueError: BF16 Mixed precision training with AMP (`--bf16`) and BF16 half precision evaluation (`--bf16_full_eval`) can only be used on CUDA, XPU 
(with IPEX), NPU or CPU/TPU/NeuronCore devices.   
```

So I removed ``--bf16 True`` from the command line, and use XLA_DOWNCAST_BF16=1:
```

XLA_DOWNCAST_BF16=1 torchrun --nproc_per_node=2 train.py  --model_id bert-base-uncased  --dataset_path lm_dataset  --lr 5e-5  --per_device_train_batch_size 16  --epochs 3

...

2024-01-27 00:25:41.000250:  30703  ERROR ||NEURON_CC_WRAPPER||: Failed compilation with ['neuronx-cc', 'compile', '--target=trn1', '--framework=XLA
', '/tmp/ubuntu/neuroncc_compile_workdir/fa7c8b8f-77f7-4632-9bcd-b22827e25d56/model.MODULE_2414376732886341633+1f673a08.hlo_module.pb', '--output', 
'/tmp/ubuntu/neuroncc_compile_workdir/fa7c8b8f-77f7-4632-9bcd-b22827e25d56/model.MODULE_2414376732886341633+1f673a08.neff', '--model-type=transforme
r-O2', '--verbose=35']: usage: neuronx-cc compile --framework {XLA} --target {trn1,inf2,trn1n} [--enable-fast-loading-neuron-binaries] [--enable-fas
t-context-switch]                                                                                                                                   
                          [--auto-cast <cast mode>] [--auto-cast-type {fp16,bf16,tf32,fp8_e4m3}] [--output <filename>] [--optlevel {1,2,3}]         
                          [--help] [--model-type {transformer,unet-inference,generic}] [--distribution-strategy {fsdp,nemo,llm-training,generic}]   
                          [--verbose {debug|info|warning|user|off}] [--logfile <filename>] [--logfile-verbose {debug|info|warning|user}]
neuronx-cc compile: error: argument --model-type: invalid choice: transformer-O2 (choose from transformer, unet-inference, generic)
```
Fixed this by going into training_utils.py and add spaces around ``{optlevel}``.

In the end it ran 500 steps before failing with ``AssertionError: data parallel group is not initialized``:

```
{'loss': 0.446, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}                                                                                                
 33%|████████████████████████████████████                                                                        | 500/1500 [45:51<05:48,  2.87it/s]2024-01-27 02:17:59
.000534:  33179  INFO ||NEURON_CACHE||: Compile cache path: /tmp/tmp136z_pau                                                                                          
2024-01-27 02:17:59.000535:  33179  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_w
orkdir/2246bb7c-d5e6-48bb-afb0-99d644c62f6e/model.MODULE_4672290115042754663+bcecdc3c.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/2246bb7c-d5e6-48bb-af
b0-99d644c62f6e/model.MODULE_4672290115042754663+bcecdc3c.neff --model-type=transformer -O2 --verbose=35                                                            
2024-01-27 02:17:59.000535:  33178  INFO ||NEURON_CACHE||: Compile cache path: /tmp/tmp136z_pau                                                                       
2024-01-27 02:17:59.000536:  33178  INFO ||NEURON_CC_WRAPPER||: Another process must be compiling /tmp/tmp136z_pau/neuronxcc-2.0.37506.0a0+dedc3e172/MODULE_46722901150
42754663+bcecdc3c/model.hlo_module.pb, been waiting for: 0.0 minutes                                                                                
.                                                                                                                                                   
Compiler status PASS                                                                                                                                
Traceback (most recent call last):                                                                                                                  
  File "train.py", line 146, in <module>                                                                                                            
    main()                                                                                                                                          
  File "train.py", line 142, in main                                                                                                                
    training_function(args)                                                                                                                         
  File "train.py", line 126, in training_function                                                                                                   
    trainer.train()                                                                                                                                 
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 1537, in train                              
    return inner_training_loop(                                                                                                                     
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/utils/require_utils.py", line 50, in wrapper                
    return func(*args, **kwargs)                                                                                                                     
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/trainers.py", line 1008, in _inner_training_loop              
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)                                                               
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/trainers.py", line 436, in _maybe_log_save_evaluate               
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)                                                                                              
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 3019, in evaluate                           
    output = eval_loop(                                                                                                                                   
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/utils/require_utils.py", line 50, in wrapper                               
    return func(*args, **kwargs)                                                                                                                     
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/trainers.py", line 1141, in evaluation_loop                                 
    dp_size = get_data_parallel_size()                                                                                                                               
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/parallel_layers/parallel_state.py", line 231, in get_data_parallel_size
    return torch.distributed.get_world_size(group=get_data_parallel_group())                                                                                         
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/parallel_layers/parallel_state.py", line 181, in get_data_parallel_group 
    assert _DATA_PARALLEL_GROUP is not None, "data parallel group is not initialized"                                                                           
AssertionError: data parallel group is not initialized       
```

**Comment by jeffhataws** [comment]
Installing with "pip install optimum-neuron" gets better results. So the instructions in https://github.com/huggingface/optimum-neuron?tab=readme-ov-file#install should be updated to remove "pip install optimum[neuron]" which installs version 0.1 always.

However, the training is still failing during evaluation with ``'NeuronTrainer' object has no attribute 'gather_function'`` (I also was able to add back ``--bf16 True``):

```
torchrun --nproc_per_node=2 train.py  --model_id bert-base-uncased  --dataset_path lm_dataset  --lr 5e-5  --per_device_train_batch_size 16 --bf16 True --epochs 3
```

```
***** Running Evaluation *****                                                                                                                
  Num examples = 2000                                                  
  Batch size = 8                                                                                                                              
2024-01-29 23:29:47.000632:  62893  INFO ||NEURON_CACHE||: Compile cache path: /tmp/tmpvfxl0n8r-O2
2024-01-29 23:29:47.000633:  62893  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/
ubuntu/neuroncc_compile_workdir/e38ae4e5-2242-42d8-a11c-8a9cfba42ec5/model.MODULE_4815110872458654697+abb26765.hlo_module.pb --output /tmp/ubu
ntu/neuroncc_compile_workdir/e38ae4e5-2242-42d8-a11c-8a9cfba42ec5/model.MODULE_4815110872458654697+abb26765.neff --model-type=transformer --ve
rbose=35            
2024-01-29 23:29:47.000648:  62892  INFO ||NEURON_CACHE||: Compile cache path: /tmp/tmpi27vmkdr-O2
2024-01-29 23:29:47.000650:  62892  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/
ubuntu/neuroncc_compile_workdir/63a315ed-ad68-4066-a0e7-eca46aea5907/model.MODULE_4815110872458654697+abb26765.hlo_module.pb --output /tmp/ubu
ntu/neuroncc_compile_workdir/63a315ed-ad68-4066-a0e7-eca46aea5907/model.MODULE_4815110872458654697+abb26765.neff --model-type=transformer --ve
rbose=35
......
Compiler status PASS

Traceback (most recent call last):                                                                                                            
  File "train.py", line 146, in <module>                               
    main()                                                                                                                                    
  File "train.py", line 142, in main                                   
    training_function(args)                                                                                                                   
  File "train.py", line 126, in training_function
    trainer.train()                                                                                                                           
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(                                                                                                               
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/utils/patching.py", line 180, in wrapper              
    return func(*args, **kwargs)                                                                                                              
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/trainers.py", line 566, in _inner_training_loop       
    return super()._inner_training_loop(                                                                                                      
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop         
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)                                           
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/trainers.py", line 373, in _maybe_log_save_evaluate   
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)                                                                                 
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 3019, in evaluate                     
    output = eval_loop(
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/neuron/trainers.py", line 588, in evaluation_loop
    return super().evaluation_loop( 
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/trainer.py", line 3217, in evaluation_loop
    losses = self.gather_function((loss.repeat(batch_size)))
AttributeError: 'NeuronTrainer' object has no attribute 'gather_function'
 33%|█████████████████████████████████▎                                                                  | 500/1500 [45:36<1:31:12,  5.47s/it]

```

**Comment by philschmid** [comment]
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!
