### ISSUE TITLE
Bugs for TGI-NeuronX DLC for llama-2 70B on Trn1.32xlarge

### ISSUE THREAD

**Issue by Neo9061** [huggingface/optimum-neuron#466]
I experienced failure using TGI-NeuronX DLC on ml.trn1.32xlarge for llama-2 70B.
* I am able to compile successfully on inf2.48xlarge with context length of 2K, batch size of 4, and TP of 24 and further deployed it successfully using TGI-NeuornX DLC.
* I am able to compile successfully on trn1.32xlarge with context length of 4K, batch size of 4, and TP of 24, but hit deployment failure with error message as below.
Do you have insights whether this is a bug on DLC side? Many thanks.

```Traceback (most recent call last): File "/usr/local/bin/text-generation-server", line 8, in <module> sys.exit(app()) File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 311, in __call__ return get_command(self)(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 778, in main return _main( File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 216, in _main rv = self.invoke(ctx) File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 683, in wrapper return callback(**use_params) # type: ignore File "/usr/local/lib/python3.10/dist-packages/text_generation_server/cli.py", line 61, in serve serve(model_id, revision, uds_path) File "/usr/local/lib/python3.10/dist-packages/text_generation_server/server.py", line 88, in serve asyncio.run(serve_inner(model_id, revision)) File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete self.run_forever() File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever self._run_once() File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once handle._run() File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.10/dist-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method return await self.intercept(
 
2024-02-06T20:53:04.365Z	> File "/usr/local/lib/python3.10/dist-packages/text_generation_server/interceptor.py", line 20, in intercept return await response File "/usr/local/lib/python3.10/dist-packages/text_generation_server/server.py", line 43, in Prefill generations, batch = self.generator.prefill(request.batch) File "/usr/local/lib/python3.10/dist-packages/text_generation_server/generator.py", line 336, in prefill raise ValueError(
 
2024-02-06T20:53:04.365Z	ValueError: Cannot prefill 1 new request(s) with only 0 empty slots.Please align the number of concurrent requests with the static batch size: 4.
```

**Comment by dacorvo** [comment]
You can get this error if you did not restrict enough the service parameters.
We are working on improving this, but for now:
--max-concurrent-requests must be set to batch size,
--max-input-length must be lower than context length,
--max-total-tokens must be set to context length (it is per-request),
--max-batch-prefill-tokens must be set to batch size * max_input_length,
--max-batch-total-tokens must be set to batch size * context length.

**Comment by Neo9061** [comment]
Thanks David, But for inf2.48xlarge deployment, I do not need explicitly specify those ENVs. Can those configs specified by information read from the config.json file?

**Comment by dacorvo** [comment]
Unfortunately no at the moment.

**Comment by dacorvo** [comment]
Possible solution in #529
