### ISSUE TITLE
ViT image classification example broken with error: cannot import name 'is_fairscale_available' from 'transformers.integrations'

### ISSUE THREAD

**Issue by kct22aws** [huggingface/optimum-neuron#480]
### System Info

```shell
optimum                       1.16.2
optimum-neuron                0.0.13
transformers                  4.37.2
transformers-neuronx          0.8.268
accelerate                    0.23.0
aws-neuronx-runtime-discovery 2.9
libneuronxla                  0.5.538
neuronx-cc                    2.11.0.34+c5231f848
neuronx-distributed           0.5.0
neuronx-hwm                   2.11.0.2+e34678757
optimum-neuron                0.0.13
torch-neuronx                 1.13.1.1.12.0
torch-xla                     1.13.1+torchneuronc
transformers-neuronx          0.8.268
*Note: Neuron version is 2.16.1 public release
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

1. Launch Inf2.8xl EC2 with U22.04. 
2. Install Neuron SDK 2.16.1 and PT1.13 per [instruction](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/neuron-setup/pytorch/neuronx/ubuntu/torch-neuronx-ubuntu22.html#pytorch-neuron-torch-neuronx-setup-on-ubuntu-22). 
3. Install public version transformers, accelerate, diffusers, scikit-learn, datasets, evaluate
4. Run [script](https://github.com/huggingface/optimum-neuron/blob/main/examples/image-classification/run_image_classification.py) found in this repo with the following command:
```
torchrun --nproc_per_node 2 run_image_classification.py \
--dataset_name food101 \
--output_dir ./food101_output/ \
--remove_unused_columns False \
--do_train \
--do_eval \
--learning_rate 2e-5 \
--num_train_epochs 1 \
--per_device_train_batch_size 16 \
--seed 100 \
--overwrite_output_dir \
--logging_steps 10
```
5. Observe output: 
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
Traceback (most recent call last):
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 31, in <module>
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 31, in <module>
        from transformers.integrations import is_fairscale_availablefrom transformers.integrations import is_fairscale_available

ImportErrorImportError: : cannot import name 'is_fairscale_available' from 'transformers.integrations' (/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/transformers/integrations/__init__.py)cannot import name 'is_fairscale_available' from 'transformers.integrations' (/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/transformers/integrations/__init__.py)

```

### Expected behavior

Expected this sample script to run without issue.

**Comment by philschmid** [comment]
This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread. Thank you!
