### ISSUE TITLE
Optimum-neuron 0.0.19: Error when exporting mistral model to inf2

### ISSUE THREAD

**Issue by thesyntaxinator** [huggingface/optimum-neuron#492]
### System Info

```shell
optimum-neuron version 0.0.19
Amazon Linux 2023
EC2 inf2.xl instance

Platform:

- Platform: Linux-6.1.75-99.163.amzn2023.x86_64-x86_64-with-glibc2.34
- Python version: 3.9.16


Python packages:

- `optimum-neuron` version: 0.0.19
- `neuron-sdk` version: 2.17.0
- `optimum` version: 1.17.1
- `transformers` version: 4.36.2
- `huggingface_hub` version: 0.20.3
- `torch` version: 1.13.1+cu117
- `aws-neuronx-runtime-discovery` version: 2.9
- `libneuronxla` version: 0.5.538
- `neuronx-cc` version: 2.11.0.34+c5231f848
- `neuronx-distributed` version: 0.5.0
- `neuronx-hwm` version: 2.11.0.2+e34678757
- `torch-neuronx` version: 1.13.1.1.12.0
- `torch-xla` version: 1.13.1+torchneuronc
- `transformers-neuronx` version: 0.8.268


Neuron Driver:

Traceback (most recent call last):
  File "/home/ec2-user/aws_neuron_venv_pytorch/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/commands/env.py", line 100, in run
    self.print_apt_pkgs()
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/commands/env.py", line 50, in print_apt_pkgs
    apt = subprocess.Popen(["apt", "list", "--installed"], stdout=subprocess.PIPE)
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'apt'
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Error when compiling mistral-based model to inf2

```
optimum-cli export neuron --model ./pytorch_model/ --task text-generation --sequence_length 4096 --batch_size 1 pytorch_model_neuron/
Traceback (most recent call last):
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers/utils/import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/neuron/modeling.py", line 47, in <module>
    from .modeling_decoder import NeuronDecoderModel
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/neuron/modeling_decoder.py", line 38, in <module>
    from transformers_neuronx.config import ContinuousBatchingConfig, NeuronConfig
ImportError: cannot import name 'ContinuousBatchingConfig' from 'transformers_neuronx.config' (/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers_neuronx/config.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/exporters/neuron/__main__.py", line 27, in <module>
    from ...neuron import NeuronModelForCausalLM
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers/utils/import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers/utils/import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.neuron.modeling because of the following error (look up to see its traceback):
cannot import name 'ContinuousBatchingConfig' from 'transformers_neuronx.config' (/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers_neuronx/config.py)
Traceback (most recent call last):
  File "/home/ec2-user/aws_neuron_venv_pytorch/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/optimum/commands/export/neuronx.py", line 226, in run
    subprocess.run(full_command, shell=True, check=True)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.neuron --model ./pytorch_model/ --task text-generation --sequence_length 4096 --batch_size 1 pytorch_model_neuron/' returned non-zero exit status 1.
```

### Expected behavior

Model should compile successfully

**Comment by JingyaHuang** [comment]
Hi @thesyntaxinator, could you upgrade your `transformers_neuronx` version, just tested with `transformers_neuronx-0.9.474`, the import should be ok.

**Comment by thesyntaxinator** [comment]
That worked, thanks!
