### ISSUE TITLE
 Python API - import NeuronStableDiffusionPipeline generates cannot import name 'retrieve_timesteps' errors

### ISSUE THREAD

**Issue by yahavb** [huggingface/optimum-neuron#598]
### System Info

```shell
Starting today (for me), following https://huggingface.co/docs/optimum-neuron/en/tutorials/stable_diffusion generates the error below. 


root@torch-serve-789d6f6786-m5frt:/# python 
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> model_id = "runwayml/stable-diffusion-v1-5"
>>> compiler_args = {"auto_cast": "matmul", "auto_cast_type": "bf16"}
>>> input_shapes = {"batch_size": 1, "height": 512, "width": 512}
>>> from optimum.neuron import NeuronStableDiffusionPipeline
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/conda/lib/python3.10/site-packages/optimum/neuron/pipelines/diffusers/__init__.py", line 22, in <module>
    from .pipeline_stable_diffusion_xl_inpaint import NeuronStableDiffusionXLInpaintPipelineMixin
  File "/opt/conda/lib/python3.10/site-packages/optimum/neuron/pipelines/diffusers/pipeline_stable_diffusion_xl_inpaint.py", line 24, in <module>
    from diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl_inpaint import (
ImportError: cannot import name 'retrieve_timesteps' from 'diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl_inpaint' (/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/conda/lib/python3.10/site-packages/optimum/neuron/modeling_diffusion.py", line 85, in <module>
    from .pipelines import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.neuron.pipelines.diffusers because of the following error (look up to see its traceback):
cannot import name 'retrieve_timesteps' from 'diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl_inpaint' (/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.neuron.modeling_diffusion because of the following error (look up to see its traceback):
Failed to import optimum.neuron.pipelines.diffusers because of the following error (look up to see its traceback):
cannot import name 'retrieve_timesteps' from 'diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl_inpaint' (/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py)
```
```


### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Installed `pip install "optimum[neuronx, diffusers]"` and followed the tutorial 

### Expected behavior

As listed in the tutorial https://huggingface.co/docs/optimum-neuron/en/tutorials/stable_diffusion

**Comment by yahavb** [comment]
I upgraded diffusers to 0.23.0 to allow height and width parameters in the **model_args. The original version that comes with optimum fixed the issue. Thanks @julien-c
