### ISSUE TITLE
Error running image classification job

### ISSUE THREAD

**Issue by mmcclean-aws** [huggingface/optimum-neuron#67]
I have the following error when running an image classification fine-tuning job on an `trn1.32xlarge`. It is was run with the following command:

The command I ran was the following:
```
torchrun --nproc_per_node=32 ~/optimum-neuron/examples/image-classification/run_image_classification.py \
    --model_name_or_path google/vit-base-patch32-224-in21k \
    --dataset_name food101 \
    --do_train \
    --do_eval \
    --bf16 True \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --save_strategy no \
    --learning_rate 5e-5 \
    --num_train_epochs 3 \
    --output_dir ~/my_awesome_food_model
```

The environment is the following:
```
(aws_neuron_venv_pytorch) [ec2-user@ip-172-31-56-159 ~]$ pip list | grep -e neuron -e xla -e torch -e optimum -e transformers
aws-neuronx-runtime-discovery 2.9
libneuronxla                  0.5.205
neuronx-cc                    2.6.0.19+3d819e565
neuronx-hwm                   2.6.0.0+826e77395
optimum                       1.8.6
optimum-neuron                0.0.4
torch                         1.13.1
torch-neuronx                 1.13.0.1.6.1
torch-xla                     1.13.0+torchneuron5
torchvision                   0.14.1
transformers                  4.28.1

(aws_neuron_venv_pytorch) [ec2-user@ip-172-31-56-159 ~]$ yum list installed | grep aws-neuron
aws-neuronx-collectives.x86_64        2.13.7.0_954e2e19b-1           @neuron    
aws-neuronx-dkms.noarch               2.9.4.0-dkms                   @neuron    
aws-neuronx-oci-hook.x86_64           2.2.0.0-1                      @neuron    
aws-neuronx-runtime-lib.x86_64        2.13.6.0_29de104d6-1           @neuron    
aws-neuronx-tools.x86_64              2.10.1.0-1                     @neuron  
```

The error trace is the following:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/parallel_loader.py", line 139, in _loader_worker
    _, data = next(data_iter)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 56, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/arrow_dataset.py", line 2782, in __getitems__
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/parallel_loader.py", line 139, in _loader_worker
    _, data = next(data_iter)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()    
batch = self.__getitem__(keys)  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data

  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/arrow_dataset.py", line 2778, in __getitem__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 56, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/arrow_dataset.py", line 2782, in __getitems__
    return self._getitem(key)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/arrow_dataset.py", line 2763, in _getitem
    batch = self.__getitem__(keys)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/arrow_dataset.py", line 2778, in __getitem__
    formatted_output = format_table(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/formatting/formatting.py", line 624, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/formatting/formatting.py", line 400, in __call__
    return self._getitem(key)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/arrow_dataset.py", line 2763, in _getitem
    return self.format_batch(pa_table)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/formatting/formatting.py", line 510, in format_batch
    return self.transform(batch)
  File "/home/ec2-user/optimum-neuron/examples/image-classification/run_image_classification.py", line 319, in train_transforms
    _train_transforms(pil_img.convert("RGB")) for pil_img in example_batch["image"]
KeyError: 'image'
    formatted_output = format_table(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/formatting/formatting.py", line 624, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/formatting/formatting.py", line 400, in __call__
    return self.format_batch(pa_table)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/datasets/formatting/formatting.py", line 510, in format_batch
    return self.transform(batch)
  File "/home/ec2-user/optimum-neuron/examples/image-classification/run_image_classification.py", line 319, in train_transforms
    _train_transforms(pil_img.convert("RGB")) for pil_img in example_batch["image"]
KeyError: 'image'
```

**Comment by umarkhalidAI** [comment]
Is there any solution to address this issue?
